source 'https://rubygems.org'

gem 'rake'
gem 'rails'
gem 'thin'
gem 'pg'
gem 'activerecord-postgres-hstore'
gem 'scrolls'
gem 'lograge'
gem 'airbrake'
gem 'newrelic_rpm'
gem 'haml-rails'
gem 'stamp'
gem 'curb'
gem 'redcarpet'
gem 'jquery-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'compass-rails'
  gem 'zazz'
  gem 'handlebars_assets'
end